### ISSUE TITLE
中文乱码问题解决方案

### ISSUE THREAD

**Issue by WangMaoren98** [LaziestDog/CUGB-SIGN#1]
**目前存在的问题：** 打卡可以正常提交，但是会出现中文乱码问题，地址和中文‘是’‘否’无法正常显示。

**解决方案：**
代码第30行，headers的Content-Type加上charset=UTF-8

**原代码**
`'Content-Type': 'application/x-www-form-urlencoded;'`
**修改后的代码**
`'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'`

**完整的headers代码**
```
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4230.1 Safari/537.36',
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
    }
```

**Comment by LaziestDog** [comment]
草，居然有人用我这个？我都本地改的，没提交上来
